trip/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tripchecker.urls')),
    path('', include('django.contrib.auth.urls'))
]

tripchecker/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = 'tripchecker'
urlpatterns = [
    path('', views.map_context, name="trips_list"),
    path('trips/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('trips/create/', login_required(views.CreateTripView.as_view()), name='new_trip'),
    path('trips/<int:pk>/update', login_required(views.UpdateView.as_view()), name='update'),
    path('trips/<int:pk>/delete', login_required(views.DeleteView.as_view()), name='delete'),
    path('sign-up', views.SignUp.as_view(), name='sign_up')

]

tripchecker/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Choices
from django.contrib.auth.models import User
from tripchecker.ninjas_api import set_coordinates



def validate_name(value):
    v = set_coordinates(str(value))

    if v.latitude() is None:
        raise ValidationError("This city is not found. Check your spelling.")
    else:
        return value

class Trips(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200,  validators=[validate_name])
    start = models.DateField()
    end = models.DateField()
    Yes = "Y"
    No = "N"
    VISIT_CHOICES = [(Yes, "Yes"), (No, "No")]
    visited = models.CharField(max_length=3, choices=VISIT_CHOICES, default=VISIT_CHOICES[1])
    description = models.CharField(max_length=200, blank=True)
    longitude = models.FloatField(default=None, null=True, blank=True)
    latitude = models.FloatField(default=None, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Trips"

    def save(self, *args, **kwargs):
        v = set_coordinates(str(self.name))
        self.longitude = v.longitude()
        self.latitude = v.latitude()
        if self.start > self.end:
            raise ValidationError("The dates are incorrect. Check the start and the end of the trip")
        super(Trips, self).save(*args, **kwargs)
    def __str__(self):
        return self.name

tripchecker/forms.py
from django.forms import HiddenInput
from tripchecker.ninjas_api import set_coordinates
from tripchecker.models import Trips
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class TripsCreateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(TripsCreateForm, self).__init__(*args, **kwargs)
        self.fields['latitude'].widget = HiddenInput()


    class Meta:
        model = Trips
        fields = ["name", "start", "end", "description", "latitude", "visited"]
        labels = {
            'name': 'City',
        }


        widgets = {
            'name': forms.TextInput(attrs={"placeholder": "City name"}),
            'start': forms.DateInput(attrs={'type': 'date'}),
            'end': forms.DateInput(attrs={'type': 'date'}),
            'description': forms.Textarea(attrs={'cols': 10, 'rows': 3}),
            'visited': forms.RadioSelect()

        }

    def clean(self):
        super(TripsCreateForm, self).clean()
        coord = self.cleaned_data
        lat = coord['latitude']
        v = set_coordinates(str(coord['name']))
        if not v.latitude():
            self._errors['name'] = self.error_class([
                'That city is not found. Please check your spelling'])

        if coord['start'] > coord['end']:
            self._errors['start'] = self.error_class([
                'The dates are incorrect. Please check the start and the end of the trip'])
        return coord

class RegistrationForm(UserCreationForm):
    username = forms.CharField(required=True, max_length=100)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

tripchecker/views.py
import datetime
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import FormView
from tripchecker.forms import RegistrationForm
from tripchecker.forms import TripsCreateForm
from tripchecker.models import *
import folium


@login_required(login_url="/login")
def map_context(request):
    places = Trips.objects.all().filter(author=request.user)
    m = folium.Map(location=[49.8419, 24.0315], zoom_start=5, height='100%', width="100%", position='relative', min_zoom=3, max_zoom=13)

    now = datetime.datetime.today()
    trips_passed = places.order_by('start').values().filter(start__lt=now)
    trips_coming = places.order_by('start').values().filter(end__gt=now)
    for place in places:
        if place.latitude and place.longitude:
            coordinates = (place.latitude, place.longitude)
            if place.start < datetime.date.today():
                if place.visited == "N":
                    folium.Marker(coordinates, popup=place.name, icon = folium.Icon(color='red', icon='asterisk')).add_to(m)
                else:
                    folium.Marker(coordinates, popup=place.name, icon = folium.Icon(color='green', icon='flag')).add_to(m)
            else:
                folium.Marker(coordinates, popup=place.name, icon=folium.Icon(color='blue', icon='info-sign')).add_to(m)

    context = {'map': m._repr_html_(), 'trips_passed': trips_passed, 'trips_coming' : trips_coming}

    return render(request, 'tripchecker/trips_list.html', context)




class DetailView(generic.DetailView):
    model = Trips
    template_name = 'tripchecker/trip_details.html'
    context_object_name = 'trip'



class UpdateView(generic.UpdateView):
    model = Trips
    form_class = TripsCreateForm
    template_name = 'tripchecker/trip_update.html'
    success_url = "/"



class DeleteView(generic.DeleteView):
    model = Trips
    template_name = 'tripchecker/trip_delete.html'
    success_url = "/"



class CreateTripView(FormView):
    template_name = "tripchecker/trips_create.html"
    form_class = TripsCreateForm
    success_url = "/"

    def form_valid(self, form):
        if form.is_valid():
            form.instance.author = self.request.user
            form.save()
            return super().form_valid(form)



class SignUp(generic.CreateView):
    form_class = RegistrationForm
    # success_url = "/"
    success_url = reverse_lazy('login')
    template_name = 'registration/sign_up.html'

trip/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{%endblock%}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'tripchecker/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>
    <div class="container-fluid px-0">
      <header class="header-c   border-bottom navbar-expand-lg d-inline-block navbar-light  col-12">
          <div class=" pb-2 d-inline-block d-lg-none">
            <a class="col-12  d-lg-none logo" href="{% url 'tripchecker:trips_list'%}">Trip Checker</a>
            <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class=" d-lg-none  menu-coll btn-customed"><b class="menu-coll ">+</b></span>
            </button>
          </div>
          <div class="collapse border-bottom navbar-collapse rounded-right" id="navbarSupportedContent">
              <a class=" border-bottom  d-none d-lg-block logo" href="{% url 'tripchecker:trips_list'%}">Trip Checker</a>
              <ul class="navbar-nav  d-inline-flex me-auto mt-1 mb-2 mb-lg-0 ">
                <li class="nav-item  ">
                    <a class="   btn-customed" href="{% url 'tripchecker:new_trip'%}"> Create new trip</a>
                 </li>
              </ul>
            <div>
                <ul class="navbar-nav   me-auto mt-1 mb-2 mb-lg-0  ">
                    {% if user.is_authenticated %}
                        <span class=" navbar-text text-white ">Hi <b>{{ user.username }}</b>! Where are you going this time?</span>
                        <li class="nav-item ">
                            <a class="nav-link px-2 " href="/logout" tabindex="-1" aria-disabled="true"><b>| Logout</b></a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link  " href="/login" tabindex="-1" aria-disabled="true"><b> Login</b></a>
                        </li>
                    {% endif %}
                </ul>
            </div>
          </div>
      </header>
        {% block content %}


        {% endblock content %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
      <footer class="d-flex flex-wrap justify-content-between align-items-center py-2 my-2 border-top">
        <div class="col-md-4 d-flex align-items-center">
            <a href="/" class="text-black mb-3  ml-2 mx-4 mb-md-0 text-body-secondary text-decoration-none lh-1">
                Home page
            </a>
            <a href="/trips/create" class="text-black mb-3  ml-2 mx-4 mb-md-0 text-body-secondary text-decoration-none lh-1">
                Create new trip
            </a>
        </div>
        <span class="mb-3 mx-4 mb-md-0 text-body-secondary">© 2023 Trip Checker</span>
      </footer>
    </div>
  </body>
</html>

tripchecker/templates/tripchecker/trip_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{%block title%}Delete trip to {{object}}{% endblock title %}
{%block content%}

    <div style="height: 85vh" class="row col-12 d-flex align-items-center">
        <div class="col-1"><p></p></div>
            <div class="col-10 align-self-center">
                <h1>Delete trip to {{object}}</h1>
                <form method="post">
                    {% csrf_token %}
                        <p class="my-5 h5">Are you sure you want to delete trip to "{{object}}"?</p>
                        <input type="submit" class="btn btn-danger me-2 btn-customed" value="Delete">
                        <button class="btn btn-warning me-2 " type="button">
                            <a class="btn-customed" href="{% url 'tripchecker:trips_list'%}">Cancel</a>
                        </button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

tripchecker/templates/tripchecker/trip_details.html
{% extends "base.html" %}
{%block title%}Trip to {{trip.name}} {% endblock title %}
{% block content %}
    <div style="height: 85vh" class="row col-12 d-flex align-items-center">
        <div class="col-1">
            <p></p>
        </div>
      <div class="col-10 align-self-center">
        <h1>Details:</h1>
        <p><b >City: </b>
            <span class="h4"> {{ trip.name }}</span>
        </p>
        <p><b>Start date:</b>
            <span class="h5"> {{ trip.start }}</span>
        </p>
        <p><b>End date:</b>
            <span class="h5"> {{ trip.end }}</span>
        </p>
        {% if trip.description %}
            <p ><b>Description:</b>
                <span class="h5"> {{ trip.description }}</span>
            </p>
        {% endif %}

        <div class="my-4">
            <button class="btn btn-success me-2 " type="button">
                <a class="btn-customed " href="{% url 'tripchecker:update' trip.id %}">Update trip</a>
            </button>
            <button class="btn btn-danger  me-2 " type="button">
                <a class="btn-customed" href="{% url 'tripchecker:delete' trip.id %}">Delete trip</a>
            </button>
            <button class="btn btn-warning  me-2 " type="button">
                <a class="btn-customed" href="{% url 'tripchecker:trips_list'%}">Cancel</a>
            </button>
        </div>
      </div>
    </div>
{% endblock content%}

tripchecker/templates/tripchecker/trip_update.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{%block title%}Update trip to {{ object.name }}{% endblock title %}
{%block content%}
    <div class="row col-12 d-flex align-items-center">
        <div class="col-1">
            <p></p>
        </div>
        <div class="col-10 align-self-center">
            <h1>Update trip to {{object.name}}</h1>
            <form method="post">
            {% csrf_token %}
                {{form|crispy}}
                <input class="btn btn-success me-2 btn-customed" type="submit" value="Update">
                <button class="btn btn-warning me-2 " type="button">
                    <a class="btn-customed" href="{% url 'tripchecker:trips_list'%}">Cancel</a>
                </button>
            </form>
        </div>
    </div>
{% endblock content %}

tripchecker/templates/tripchecker/trips_create.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{%block title%}Create new trip{% endblock title %}
{% load crispy_forms_tags %}
{%block content%}
    <div class="row col-12 d-flex align-items-center">
        <h1>Create new trip</h1>
        <div class="col-1"><p></p></div>
        <form method="post" class="col-10 align-self-center">
            {% csrf_token %}
            {{form|crispy}}
            <input class="btn btn-success me-2 btn-customed d-inline-block" type="submit" value="Create Trip">
            <button class="btn btn-warning me-2 d-inline-block " type="button">
                <a class="btn-customed" href="{% url 'tripchecker:trips_list'%}">Cancel</a>
            </button>
        </form>
    </div>
{% endblock content %}

tripchecker/templates/tripchecker/trips_list.html
{% extends "base.html" %}
{% block title%}All trips{% endblock title %}
{% block content %}
    <div class="row align-items-center">
        <h1>Trips</h1>
    </div>
    <div class="row d-flex ">
        <div class="col-xs-12 col-md-6 align-items-center text-center px-5">
            {% if trips_coming %}
                <h2 class="">Upcoming</h2>
                <div class="pt-3 ">
                    {% for t in trips_coming %}
                        <p class="text-start">  <a class="trips" href="{% url 'tripchecker:detail' t.id %}" > <span class="h4">{{ t.name }}</span> <span class="text-black-50 text-secondary"> ---- {{ t.start }} - {{ t.end }}</span></a></p>
                    {% endfor %}
                </div>
            {% else %}
                <h3 class="pt-3">Planning to go anywhere?</h3>
            {% endif %}
            <button class=" my-2 btn btn-success  " type="button">
                <a class="btn-customed" href="{% url 'tripchecker:new_trip'%}"> Add upcoming trip</a>
            </button>
        </div>
        <div class="col-xs-12 col-md-6 align-items-center text-center">
            {% if trips_passed %}
                <h2>Passed</h2>
                <div class="pt-3 ">
                     {% for t in trips_passed %}
                        <p class="text-start">  <a class="trips" href="{% url 'tripchecker:detail' t.id %}" > <span class="h4">{{ t.name }}</span> <span class="text-black-50 text-secondary"> ---- {{ t.start }} - {{ t.end }}</span></a></p>
                     {% endfor %}
                </div>
            {% else %}
                 <h3 class="pt-3">Had any trips in the past?</h3>
            {% endif %}
            <button class=" my-2 btn btn-success  " type="button">
                <a class="btn-customed" href="{% url 'tripchecker:new_trip'%}"> Add visited places</a>
            </button>
        </div>
    </div>
    <div class="m-4 h-auto" >
        {{ map | safe }}
    </div>
{% endblock content %}